### PR TITLE
workaround for svg jupyter issue

### PR DESCRIPTION
**Pull request by pedritomelenas**
Workaroung for svg displaying problems in jupyter https://github.com/jupyterlab/jupyterlab/issues/10464

### CODE REVIEW

**Comment by pedritomelenas** [comment]
Please, do not merge. If the svg is too big it will be cut. 
This does not happen in vscode, but it does on any browseer.
I am trying to figure out how to bring up a scroll bar in this case.

**Comment by pedritomelenas** [comment]
now it seems to work; there was also a problem with "-o" in Linux; it works for macos

**Comment by pedritomelenas** [comment]
Did some changes. For some reason the output of `Base64String` was not usable under macos, and so I rely on `base64 -i`. @ManuelAFDelgado, please check!

**Comment by ManuelAFDelgado** [comment]
Everything works perfectly with the examples I checked. Thank you @pedritomelenas.

**Review by olexandr-konovalov — APPROVED** [review]

**Pull request merged**
