### PR TITLE
Clean up setup.py

### PR DESCRIPTION
**Pull request by isuruf**
You can run this script as `pip install .` or `pip install --user`

### CODE REVIEW

**Comment by alex-konovalov** [comment]
Thanks @isuruf! Could you please explain the purpose of `gap-mode.json` and also of the Binder addition?

**Comment by isuruf** [comment]
`gap-mode.json` is there so that the gap nbextension is enabled automatically with notebook>=5.3. No need to do enable the extension after installing anymore.

Binder lets users try the jupyter notebook on cloud. See https://mybinder.org/v2/gh/isuruf/GapJupyterKernel/binder?filepath=demos%2Fgraph-visjs.ipynb

**Comment by isuruf** [comment]
These changes also let you publish this package in PyPI.

**Comment by alex-konovalov** [comment]
I use binder, see e.g. https://github.com/alex-konovalov/gap-teaching - I mean, what's the benefit of adding the files to support binder into the package?

**Comment by isuruf** [comment]
Adding it here means, people can try out new features in this package. I can remove it if you want.

**Comment by alex-konovalov** [comment]
I would prefer to add Binder support in a separate PR, and also would have questions about its current proposal. By the way, we have https://github.com/gap-system/try-gap-in-jupyter where users may try it, and it would be good to add a binder badge to the README in _this_ repo, but I'd prefer to use `gapsystem/gap-docker` from Docker Hub to run it.

**Comment by alex-konovalov** [comment]
It will be useful to describe why egg needs to be disabled. This package has no fixed maintainer at the moment, so please help us to understand this PR by giving some more details.

**Comment by isuruf** [comment]
Sure. The `data_files` argument with `etc` or `share` directories doesn't work when building an egg. You need to use `pip install .` which creates a wheel first and then installs the package. This is what other nbextension packages like `nbconvert`, `pari_jupyter` does.

See https://github.com/jupyter/nbconvert/blob/master/setup.py and https://github.com/jdemeyer/pari_jupyter/blob/master/setup.py

**Comment by alex-konovalov** [comment]
Thanks @isuruf. Does this change any installation instructions? Do we need to test this manually, or the fact that .travis.yml changes result in passing tests should suffice?

**Comment by isuruf** [comment]
> Does this change any installation instructions?

Yes. You need to do `pip install .` instead of `python setup.py install`

**Comment by alex-konovalov** [comment]
In which case, could you please also change instructions in https://github.com/gap-packages/JupyterKernel/blob/master/doc/intro.xml ?

**Comment by alex-konovalov** [comment]
@isuruf sorry, this was approved long time ago but not merged. Would you mind to rebase it to test again? In the meantime, we switched from Travis to GitHub actions, so that may need an update.

**Comment by alex-konovalov** [comment]
I've tested it locally, seems working, so I've dropped the commit changing `.travis.yml` and pushed the rest in 4 commits to the master: c671159157d80e57b90bea5df916284b03930890, a8ce174df5f7b595090cd46d7dc08f59d0c2c1ab, ab45c2ea2b609fb85078e364981098359e57a416 and dad85566bdfc52aef19eef8db70b0d6702b24151. CI tests pass, although they do not install the Jupyter part at all - they only test the GAP side of things, but we should be testing this in various other settings from now on.

**Comment by alex-konovalov** [comment]
> These changes also let you publish this package in PyPI.

@isuruf I am not sure we need it - what would be the hypothetical use of `pip3 install jupyter-kernel-gap` if there is no GAP on the user's machine? And if there is GAP with packages, then this package is already in `pkg` subdirectory of their GAP installation. Or do I miss something?

**Pull request closed without merging**
